apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: flask-mongodb-ns
type: Opaque
data:
  # Base64 encoded values
  # Username: admin (base64: YWRtaW4=)
  # Password: password123 (base64: cGFzc3dvcmQxMjM=)
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQxMjM=