apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: flask-mongodb-ns
  labels:
    app: mongodb
spec:
  # Access mode - must match or be subset of PV's access modes
  accessModes:
    - ReadWriteOnce
  
  # Storage class - must match PV's storageClassName for binding
  storageClassName: standard
  
  # Resources - how much storage we're requesting
  resources:
    requests:
      storage: 1Gi  # Request 1 GiB (PV has 2Gi, so this will fit)
  
  selector:
    matchLabels:
      app: mongodb
      type: local